package com.example.demo.enums;

public enum ContractorField {
    ROAD_CONSTRUCTION,
    RESIDENTIAL_CONSTRUCTION,
    COMMERCIAL_CONSTRUCTION,
    INDUSTRIAL_CONSTRUCTION,
    ELECTRICAL_CONTRACTING,
    PLUMBING,
    HVAC,
    ROOFING,
    LANDSCAPING,
    GENERAL_CONTRACTING;
}
